project:
  type: website
  output-dir: docs

website:
  title: "Financial Data Exploration"
  navbar:
    left:
      - text: Home
        href: website/index.qmd
      - text: Financial Statement Data Scoping
        menu:
          - text: 2024 Q1 Submission Data Report
            href: website/q1-submissions.qmd
          - text: 2024 Q1 Numeric Data Report
            href: website/q1-numbers.qmd
      - text: Financial Statement Data Analysis
        menu:
          - text: Filer Status Comparison
            href: website/filer-status-comparison.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



